# julia as a cli calculator

This Jupyter notebook contains all the input code snippets from [julia as a cli calculator](https://krasjet.com/rnd.wlk/julia/). However, notice that some code blocks are not written in Julia, and some are not compatible with Jupyter, so use at your own risk.

The original article is not written in Jupyter. This notebook is here just for your convenience.

In [ ]:
7 / 4

In [ ]:
x = ans + 2im

In [ ]:
exp(x)

In [ ]:
A = [1 2 3; 4 5 6]

In [ ]:
A = [1 2 3
     4 5 6]

In [ ]:
A * [3; 2; 1]

In [ ]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6]])
A @ np.array([[1,2,3]]).T

In [ ]:
for i = 1:6
  println(A[i])
end

In [ ]:
for i in 1:3
  println(i)
end

In [ ]:
for i ∈ 1:0.5:2
  println(i)
end

In [ ]:
help?> ℝ

In [ ]:
help?> apropos

In [ ]:
for a ∈ A
  println(a)
end

In [ ]:
[a^2 for a ∈ A]

In [ ]:
v1 = [0.5; 0.5]
v2 = [1.5; 0.5]
v3 = [0.5; 1.5]

In [ ]:
V = [v1 v2 v3]

In [ ]:
# ℝ → ℝ^(2×2)
R(θ) = [cos(θ) -sin(θ); sin(θ) cos(θ)]

In [ ]:
R(π/3)

In [ ]:
# ℝ^2 → ℝ^2
rotate(v) = R(π/3) * v

In [ ]:
rotate(v1)

In [ ]:
# ℝ → ℝ^2 (?)
dup = x -> [x;x]

In [ ]:
map(dup, V)

In [ ]:
map(dup, map(dup, V))

In [ ]:
dup([1 2; 3 4])

In [ ]:
@which [1;1]

In [ ]:
@which [v1;v1]

In [ ]:
[V v1; v2 V]

In [ ]:
cols = eachcol(V)

In [ ]:
collect(cols)

In [ ]:
V′ = map(rotate, eachcol(V))

In [ ]:
V′ = rotate.(eachcol(V))

In [ ]:
exp.([1,2,3,4])

In [ ]:
[1,2,3,4] .* [4,3,2,1]

In [ ]:
.*([1,2,3,4], [4,3,2,1])

In [ ]:
# Vector → String
cleanup(v) = join(round.(v, digits=5), ", ")

In [ ]:
1 |> exp |> sin

In [ ]:
sin(exp(1))

In [ ]:
[1,2,3] .|> exp .|> sin

In [ ]:
[1,2,3] .|> [exp sin]

In [ ]:
[exp(1) sin(1); exp(2) sin(2); exp(3) sin(3)]

In [ ]:
# (String, ℤ) → String
encrypt(str, key) = (
                      str                     |>
                      collect                .|>
                     (x -> x - 'a')          .|>
                     (x -> mod(x + key, 26)) .|>
                     (x -> x + 'a')
                    )                         |>
                      join

In [ ]:
(1, 2) .|> x -> x^2 |> sum

In [ ]:
(1, 2) .|> (x -> x^2) |> sum

In [ ]:
encrypt("hellojulia", 20)

In [ ]:
V′                         .|>
(x -> round.(x, digits=5))  |>
(x -> join(x, ", "))        |>
println

In [ ]:
V′                         .|>
(x -> round.(x, digits=5))  |>
(x -> join(x, ", "))        |>
println;

In [ ]:
map (3*) [1,2,3]

In [ ]:
curry = Base.Fix2
map(curry(*,3), [1,2,3])

In [ ]:
V′                  .|>
round.(_, digits=5)  |>
join(_, ", ")        |>
println

In [ ]:
eachcol(V) .|> rotate .|> cleanup .|> println;

In [ ]:
2.1.2 Desugaring the array syntax

In [ ]:
A = [1 2 3; 4 5 6]

In [ ]:
Array{Integer,2} == Matrix{Integer}

In [ ]:
B = [[1, 4], [2, 5], [3, 6]]

In [ ]:
Array{Array{Integer,1},1} == Vector{Vector{Integer}}

In [ ]:
A == B

In [ ]:
Matrix{Integer} == Vector{Vector{Integer}}

In [ ]:
# List (Array)
[1,2,3]

In [ ]:
# Column vector
[1;2;3]

In [ ]:
# Row vector
[1 2 3]

In [ ]:
[1,2,3] == [1;2;3]

In [ ]:
1:3 == [1;2;3]

In [ ]:
[1,2,3; 4,5,6]

In [ ]:
[1,2,3; 4,5,6]

In [ ]:
[1 2; 3 4] * [1,1]

In [ ]:
[[1,2], [3,4], [5,6]]

In [ ]:
[[1,2]; [3,4]; [5,6]]

In [ ]:
[[1 2] [3 4] [5 6]]

In [ ]:
[[1 2], [3 4], [5 6]]

In [ ]:
[[1;2] [3;4] [5;6]]

In [ ]:
# A list of a single number
a = [1]

In [ ]:
# More lists of a single number
b = [2]
c = [3]
d = [4]

In [ ]:
# Vertical concatenation of horizontal concatenations of lists
# of lists of a single number
[[a] [b]; [c] [d]]

In [ ]:
# Vertical concatenation of lists of a single number
[a; b]

In [ ]:
# Matrix multiplication of
# (vertical concatenation of horizontal concatenations of lists
# of lists of a single number)
# and
# (vertical concatenation of lists of a single number)
[[a] [b]; [c] [d]] * [a; b]

In [ ]:
Meta.show_sexpr(:([1,2,3]))

In [ ]:
Meta.show_sexpr(:([1;2;3]))

In [ ]:
Meta.show_sexpr(:([1 2 3]))

In [ ]:
'vcat

In [ ]:
'1

In [ ]:
:vcat

In [ ]:
:1

In [ ]:
`(+ 1 2)

In [ ]:
`(+ ,(+ 1 3) 2)

In [ ]:
:(1 + 2)

In [ ]:
:($(1 + 3) + 2)

In [ ]:
eval(:($(1 + 3) + 2))

In [ ]:
@. [1,2,3] |> exp |> sin

In [ ]:
Meta.show_sexpr(:([1 2 3; 4 5 6]))

In [ ]:
@edit [1 2 3; 4 5 6]

In [ ]:
Meta.show_sexpr(:([[1,4], [2,5], [3,6]]))

In [ ]:
@edit [[1,4], [2,5], [3,6]]

In [ ]:
ndims(V)

In [ ]:
eachslice(V, dims=2) |> collect

In [ ]:
V

In [ ]:
row, col = size(V)

In [ ]:
V[1,2]

In [ ]:
V[[1,2], 2]

In [ ]:
V[[1 2], 2]

In [ ]:
V[[1 2; 2 1], 2]

In [ ]:
map(i -> V[i,2], [1 2; 2 1])

In [ ]:
V[:,2]

In [ ]:
[V[:,1] V[:,2] V[:,3]] == V

In [ ]:
map(i -> V[:,i], 1:3)

In [ ]:
mapslices(rotate, V, dims=1)

In [ ]:
mapslices(sum, V, dims=2)

In [ ]:
T = rand(3,3,3)
map(i -> T[:,i,:], 1:3) == eachslice(T, dims=2) |> collect

In [ ]:
2.2 The imperative approach

In [ ]:
for v ∈ eachcol(V)
  v |> rotate |> cleanup |> println
end

In [ ]:
[v |> rotate |> cleanup for v ∈ eachcol(V)]

In [ ]:
for i ∈ 1:size(V,2)
  V[:,i] |> rotate |> cleanup |> println
end

In [ ]:
# a large matrix
A = rand(1000, 1000);
# trigger JIT compilation, as will be explained later
A[:,1];

@allocated A[:,1]

In [ ]:
# trigger JIT compilation, as will be explained later
view(A,:,1);

@allocated view(A,:,1)

In [ ]:
# trigger JIT compilation, as will be explained later
@view A[:,1];

@allocated @view A[:,1]

In [ ]:
for i ∈ 1:size(V,2)
  view(V,:,i) |> rotate |> cleanup |> println
end

In [ ]:
@views for i ∈ 1:size(V,2)
         V[:,i] |> rotate |> cleanup |> println
       end

In [ ]:
R(π/3) * V

In [ ]:
ans'

In [ ]:
using LinearAlgebra
det(R(π/3))

In [ ]:
π/3 |> R |> det

In [ ]:
V .- V[:,1]

In [ ]:
V .+ V[1,:]'

In [ ]:
V[1,:]'

In [ ]:
V .+ V[1,1]

In [ ]:
R(π/3) * (V .- V[:,1]) .+ V[:,1]

In [ ]:
c = V * [1;1;1]/3

In [ ]:
reduce(+, V / 3, dims=2)

In [ ]:
V[1,:]

In [ ]:
reduce(*, V, dims=2).^(1/size(V,2))

In [ ]:
R(π/3) * (V .- c) .+ c

In [ ]:
translate(t) = v -> v + t
rotate(θ) = v -> R(θ)*v

eachcol(V) .|> translate(-v1) .|> rotate(π/3) .|> translate(v1)

In [ ]:
(@v1.4) pkg> add Grassmann

In [ ]:
using Grassmann

In [ ]:
@basis S"∞∅++" G31 e

In [ ]:
e1 + 2*e2

In [ ]:
[e1 e2] * V

In [ ]:
W = ans |> transpose

In [ ]:
↑(0.5*e1 + 0.5*e2)

In [ ]:
𝕚 = e12

In [ ]:
𝕚^2

In [ ]:
↓(↑(0.5*e1 + 0.5*e2) ⊘ exp(𝕚*(π/3)/2))

In [ ]:
# rotation angle
θ = π/3
# displacement vector
t = W[1]

.↑(W) .⊘ exp(-t*e∞/2) .⊘ exp(𝕚*θ/2) .⊘ exp(t*e∞/2) .|> ↓

In [ ]:
@. ↑(W) ⊘ exp(-t*e∞/2) ⊘ exp(𝕚*θ/2) ⊘ exp(t*e∞/2) |> ↓

In [ ]:
T = exp(-t*e∞/2) * exp(𝕚*θ/2) * exp(t*e∞/2)

In [ ]:
@. ↑(W) ⊘ T |> ↓

In [ ]:
(@v1.4) pkg> add UnicodePlots

In [ ]:
using UnicodePlots

In [ ]:
# of course, there is no `cycle` command
# so we have to add an extra vertex
U = [V v1]
lineplot( U[1,:], U[2,:]             # x, y
        , xlim=(-2,2), ylim=(-2,2)
        , border=:none, labels=false
        , width=30
        )

In [ ]:
U′ = R(π/3) * U

In [ ]:
lineplot( U′[1,:], U′[2,:]           # x, y
        , xlim=(-2,2), ylim=(-2,2)
        , border=:none, labels=false
        , width=30
        )

In [ ]:
@vars θ x y real=true

In [ ]:
w = R(θ) * [x;y]

In [ ]:
using LinearAlgebra
norm(w) |> simplify |> print

In [ ]:
V |> latexify |> print

In [ ]:
:(sqrt(θ/3 + exp(ϕ^2))) |> latexraw |> print

In [ ]:
bin(0xce - 5)

In [ ]:
dec(0xf1) |> print

In [ ]:
$ time julia hello.jl

In [ ]:
$ time julia --startup-file=no hello.jl

In [ ]:
@time println("hello, julia")

In [ ]:
@time println("hello, julia")

In [ ]:
@time println("bye, julia")

In [ ]:
@time println([1,2,3,4])

In [ ]:
@time println([1,2,3,4])

In [ ]:
$ time julia hello.jl

In [ ]:
hex(0b11110) |> print

In [ ]:
@vars θ x y real=true

In [ ]:
:(sqrt(θ/3 + exp(ϕ^2))) |> latexraw |> print

In [ ]:
eigen([1 2; 3 4])

In [ ]:
exit()

In [ ]:
$ head -n 5 precompile.jl

In [ ]:
using PackageCompiler
create_sysimage( [:SymPy, :LinearAlgebra, :Latexify]
               , sysimage_path="sys_calc.so"
               , precompile_statements_file="precompile.jl"
               )

In [ ]:
$ julia -Jsys_calc.so

In [ ]:
$ jl

In [ ]:
:ℝ |> clipboard

In [ ]:
"∃" |> clipboard

In [ ]:
macro clip(symb)
  :(clipboard($symb))
end

In [ ]:
@clip :ℂ

In [ ]:
@clip :❤